language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t willvac/vehicles-api-test -f Dockerfile.dev .
    
script:
    - docker run willvac/vehicles-api-test mvn test

after_success:
    - docker build -t willvac/vehicles-api -f Dockerfile.prod .

    # Login to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push willvac/vehicles-api


